list = []
print('Enter 10 numbers: ')
num1 = int(input('Enter number 1: '))
list.append(num1)
num2 = int(input('Enter number 2: '))
list.append(num2)
num3 = int(input('Enter number 3: '))
list.append(num3)
num4 = int(input('Enter number 4: '))
list.append(num4)
num5 = int(input('Enter number 5: '))
list.append(num5)
num6 = int(input('Enter number 6: '))
list.append(num6)
num7 = int(input('Enter number 7: '))
list.append(num7)
num8 = int(input('Enter number 8: '))
list.append(num8)
num9 = int(input('Enter number 9: '))
list.append(num9)
num10 = int(input('Enter number 10: '))
list.append(num10)
print(list)

order = input('Would you like this list to be printed in ascending (A) or descending (D) order? \nChoice: ')
if order == 'A':
    list.sort() 
    print(list) 
elif order == 'D':
    list.sort(reverse=True)
    print(list)
else:
    print('Invalid selection! Terminating process...')
    quit()
